services:
  - type: web
    name: sat-simulation
    env: python
    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: sat-simulation-db
          property: connectionString

databases:
  - name: sat-simulation-db
    databaseName: sat_simulation
    user: sat_user