"""Add section_start_time to TestSession

Revision ID: 37c91087b41d
Revises: 
Create Date: 2025-07-19 15:42:46.178108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37c91087b41d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_start_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_session', schema=None) as batch_op:
        batch_op.drop_column('section_start_time')

    # ### end Alembic commands ###
