"""initial

Revision ID: 6069707e0181
Revises: 
Create Date: 2026-03-28 12:46:48.962481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6069707e0181'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('test_session')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_session',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('practice_test_id', sa.VARCHAR(length=10), nullable=False),
    sa.Column('start_time', sa.DATETIME(), nullable=False),
    sa.Column('score', sa.INTEGER(), nullable=True),
    sa.Column('answers', sa.TEXT(), nullable=True),
    sa.Column('current_question', sa.INTEGER(), nullable=True),
    sa.Column('current_section', sa.INTEGER(), nullable=True),
    sa.Column('marked_for_review', sa.TEXT(), nullable=True),
    sa.Column('section_start_time', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('password', sa.VARCHAR(length=120), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
