"""add drill feature tables

Revision ID: 7a7422cba674
Revises: 8075f4a9330d
Create Date: 2026-03-28 16:03:05.876596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a7422cba674'
down_revision = '8075f4a9330d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drill_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(length=100), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('section_type', sa.String(length=20), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('num_questions', sa.Integer(), nullable=False),
    sa.Column('question_ids', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drill_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drill_sets_topic_name'), ['topic_name'], unique=False)
        batch_op.create_index('ix_drill_topic_difficulty', ['topic_name', 'difficulty'], unique=False)

    op.create_table('drill_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('drill_set_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('answers', sa.Text(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('accuracy_percent', sa.Float(), nullable=True),
    sa.Column('use_timer', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['drill_set_id'], ['drill_sets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drill_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drill_sessions_drill_set_id'), ['drill_set_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drill_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('drill_set_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(length=100), nullable=False),
    sa.Column('total_attempts', sa.Integer(), nullable=True),
    sa.Column('completed_sets', sa.Integer(), nullable=True),
    sa.Column('best_score', sa.Float(), nullable=True),
    sa.Column('last_attempt_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_name', name='uq_user_topic')
    )
    with op.batch_alter_table('drill_set_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drill_set_progress_topic_name'), ['topic_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_drill_set_progress_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_user_progress', ['user_id', 'topic_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drill_set_progress', schema=None) as batch_op:
        batch_op.drop_index('ix_user_progress')
        batch_op.drop_index(batch_op.f('ix_drill_set_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_drill_set_progress_topic_name'))

    op.drop_table('drill_set_progress')
    with op.batch_alter_table('drill_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drill_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_drill_sessions_drill_set_id'))

    op.drop_table('drill_sessions')
    with op.batch_alter_table('drill_sets', schema=None) as batch_op:
        batch_op.drop_index('ix_drill_topic_difficulty')
        batch_op.drop_index(batch_op.f('ix_drill_sets_topic_name'))

    op.drop_table('drill_sets')
    # ### end Alembic commands ###
