"""add text highlights

Revision ID: 8075f4a9330d
Revises: 6069707e0181
Create Date: 2026-03-28 13:20:07.455691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8075f4a9330d'
down_revision = '6069707e0181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_highlights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('test_session_id', sa.Integer(), nullable=False),
    sa.Column('section_idx', sa.Integer(), nullable=False),
    sa.Column('question_idx', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(length=20), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('selected_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['test_session_id'], ['test_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('text_highlights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_text_highlights_question_idx'), ['question_idx'], unique=False)
        batch_op.create_index(batch_op.f('ix_text_highlights_section_idx'), ['section_idx'], unique=False)
        batch_op.create_index(batch_op.f('ix_text_highlights_test_session_id'), ['test_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_text_highlights_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_highlights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_text_highlights_user_id'))
        batch_op.drop_index(batch_op.f('ix_text_highlights_test_session_id'))
        batch_op.drop_index(batch_op.f('ix_text_highlights_section_idx'))
        batch_op.drop_index(batch_op.f('ix_text_highlights_question_idx'))

    op.drop_table('text_highlights')
    # ### end Alembic commands ###
