"""initial schema (sat)

Revision ID: 8a8a895e0716
Revises: 
Create Date: 2026-09-26 09:53:00.701525

"""
from alembic import op
import sqlalchemy as sa
from flask import current_app

# `sat` on Supabase/Postgres, None on local SQLite (see DB_SCHEMA in app.py)
SCHEMA = current_app.config.get("DB_SCHEMA")
PREFIX = f"{SCHEMA}." if SCHEMA else ""


# revision identifiers, used by Alembic.
revision = '8a8a895e0716'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    if SCHEMA:
        # Only the Flask backend should read these tables. Make sure Supabase's
        # public API roles can't reach them even if the schema is exposed later.
        op.execute(f"""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
                    EXECUTE 'REVOKE ALL ON SCHEMA "{SCHEMA}" FROM anon, authenticated';
                END IF;
            END $$;
        """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drill_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(length=100), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('section_type', sa.String(length=20), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('num_questions', sa.Integer(), nullable=False),
    sa.Column('question_ids', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema=SCHEMA
    )
    with op.batch_alter_table('drill_sets', schema=SCHEMA) as batch_op:
        batch_op.create_index('ix_drill_topic_difficulty', ['topic_name', 'difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_sat_drill_sets_topic_name'), ['topic_name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('supabase_user_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema=SCHEMA
    )
    with op.batch_alter_table('users', schema=SCHEMA) as batch_op:
        batch_op.create_index(batch_op.f('ix_sat_users_supabase_user_id'), ['supabase_user_id'], unique=True)

    op.create_table('drill_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('drill_set_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('answers', sa.Text(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('accuracy_percent', sa.Float(), nullable=True),
    sa.Column('use_timer', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['drill_set_id'], [f'{PREFIX}drill_sets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], [f'{PREFIX}users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema=SCHEMA
    )
    with op.batch_alter_table('drill_sessions', schema=SCHEMA) as batch_op:
        batch_op.create_index(batch_op.f('ix_sat_drill_sessions_drill_set_id'), ['drill_set_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sat_drill_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('drill_set_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(length=100), nullable=False),
    sa.Column('total_attempts', sa.Integer(), nullable=True),
    sa.Column('completed_sets', sa.Integer(), nullable=True),
    sa.Column('best_score', sa.Float(), nullable=True),
    sa.Column('last_attempt_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [f'{PREFIX}users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_name', name='uq_user_topic'),
    schema=SCHEMA
    )
    with op.batch_alter_table('drill_set_progress', schema=SCHEMA) as batch_op:
        batch_op.create_index(batch_op.f('ix_sat_drill_set_progress_topic_name'), ['topic_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_sat_drill_set_progress_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_user_progress', ['user_id', 'topic_name'], unique=False)

    op.create_table('test_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('practice_test_id', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('answers', sa.Text(), nullable=True),
    sa.Column('current_question', sa.Integer(), nullable=True),
    sa.Column('current_section', sa.Integer(), nullable=True),
    sa.Column('marked_for_review', sa.Text(), nullable=True),
    sa.Column('section_start_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [f'{PREFIX}users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema=SCHEMA
    )
    op.create_table('text_highlights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('test_session_id', sa.Integer(), nullable=False),
    sa.Column('section_idx', sa.Integer(), nullable=False),
    sa.Column('question_idx', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(length=20), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('selected_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['test_session_id'], [f'{PREFIX}test_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], [f'{PREFIX}users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema=SCHEMA
    )
    with op.batch_alter_table('text_highlights', schema=SCHEMA) as batch_op:
        batch_op.create_index(batch_op.f('ix_sat_text_highlights_question_idx'), ['question_idx'], unique=False)
        batch_op.create_index(batch_op.f('ix_sat_text_highlights_section_idx'), ['section_idx'], unique=False)
        batch_op.create_index(batch_op.f('ix_sat_text_highlights_test_session_id'), ['test_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sat_text_highlights_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('text_highlights', schema=SCHEMA) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sat_text_highlights_user_id'))
        batch_op.drop_index(batch_op.f('ix_sat_text_highlights_test_session_id'))
        batch_op.drop_index(batch_op.f('ix_sat_text_highlights_section_idx'))
        batch_op.drop_index(batch_op.f('ix_sat_text_highlights_question_idx'))

    op.drop_table('text_highlights', schema=SCHEMA)
    op.drop_table('test_sessions', schema=SCHEMA)
    with op.batch_alter_table('drill_set_progress', schema=SCHEMA) as batch_op:
        batch_op.drop_index('ix_user_progress')
        batch_op.drop_index(batch_op.f('ix_sat_drill_set_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_sat_drill_set_progress_topic_name'))

    op.drop_table('drill_set_progress', schema=SCHEMA)
    with op.batch_alter_table('drill_sessions', schema=SCHEMA) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sat_drill_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sat_drill_sessions_drill_set_id'))

    op.drop_table('drill_sessions', schema=SCHEMA)
    with op.batch_alter_table('users', schema=SCHEMA) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sat_users_supabase_user_id'))

    op.drop_table('users', schema=SCHEMA)
    with op.batch_alter_table('drill_sets', schema=SCHEMA) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sat_drill_sets_topic_name'))
        batch_op.drop_index('ix_drill_topic_difficulty')

    op.drop_table('drill_sets', schema=SCHEMA)
    # ### end Alembic commands ###
